export const ActionTypes = {
  //PRODUCTS
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCT: "GET_PRODUCT",
  GET_DICOUNT_PRODUCTS:"GET_DICOUNT_PRODUCTS",
  GET_NEW_PRODUCTS:"GET_NEW_PRODUCTS",
  GET_BEST_SELLING_PRODUCTS:"GET_BEST_SELLING_PRODUCTS",
  GET_TOP_RATED_PRODUCTS:"GET_TOP_RATED_PRODUCTS",
  GET_MOST_POPULAR_PRODUCTS:"GET_MOST_POPULAR_PRODUCTS",



  GET_CATEGORIES: "GET_CATEGORIES",

  // CART

  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  TOTAL_PRICE: "TOTAL_PRICE",
};
