export const ActionTypes = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCT: "GET_PRODUCT",

  GET_CATEGORIES: "GET_CATEGORIES",

  // CART

  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  TOTAL_PRICE: "TOTAL_PRICE",
};
