module.exports = {
  navLinks: [
    {
      name: "home",
      children: [],
      icon: "",
      url: "/",
    },
    {
      name: "products",
      children: [],
      icon: "",
      url: "/products",
    },
    {
      name: "categories",
      children: [
        {
          name: "Accessories & Supplies",
          children: [],
          icon: "",
          url: "/Women",
        },
        {
          name: "Camera & Photo",
          children: [],
          icon: "",
          url: "/Women",
        },
        {
          name: "Car & Vehicle Electronics",
          children: [],
          icon: "",
          url: "/Women",
        },
        {
          name: "Cell Phones & Accessories",
          children: [],
          icon: "",
          url: "/Women",
        },
        {
          name: "Computers & Accessories",
          children: [],
          icon: "",
          url: "/Women",
        },
        {
          name: "GPS & Navigation",
          children: [],
          icon: "",
          url: "/Women",
        },
        {
          name: "Headphones",
          children: [],
          icon: "",
          url: "/Women",
        },
        {
          name: "Home Audio",
          children: [],
          icon: "",
          url: "/Women",
        },
        {
          name: "Office Electronics",
          children: [],
          icon: "",
          url: "/Women",
        },
      ],
      icon: true,
      url: "/women",
    },
    {
      name: "fags",
      children: [],
      icon: "",
      url: "/fags",
    },
    {
      name: "about",
      children: [],
      icon: "",
      url: "/about",
    },
    {
      name: "contact",
      children: [],
      icon: "",
      url: "/contact",
    },
  ],
  categories: [
    {
      name: "Accessories & Supplies",
      categoryId: 1,
      icon: "",
      url: "/women",
    },
    {
      name: "Camera & Photo",
      categoryId: 2,
      icon: "",
      url: "/women",
    },
    {
      name: "Car & Vehicle Electronics",
      categoryId: 3,
      icon: "",
      url: "/women",
    },
    {
      name: "Cell Phones & Accessories",
      categoryId: 4,
      icon: "",
      url: "/women",
    },
    {
      name: "Computers & Accessories",
      categoryId: 5,
      icon: "",
      url: "/women",
    },
    {
      name: "GPS & Navigation",
      categoryId: 6,
      icon: "",
      url: "/women",
    },
    {
      name: "Headphones",
      categoryId: 7,
      icon: "",
      url: "/women",
    },
    {
      name: "Home Audio",
      categoryId: 8,
      icon: "",
      url: "/women",
    },
    {
      name: "Office Electronics",
      categoryId: 9,
      icon: "",
      url: "/women",
    },
  ],
  contactInfo: [
    {
      name: "685 Market Street",
      icon: "",
      link: "/",
    },
    {
      name: "Cosmopolis, CA 94105, United States",
      icon: "",
      link: "/",
    },
    { name: "1.800.000.6690", icon: "fas fa-phone", link: "/" },
    {
      name: "support@electronry.com",
      icon: "fas fa-envelope",
      link: "/",
    },
  ],
  furtherInfo: [
    { name: "About", icon: "", link: "/" },
    {
      name: "Customer Service",
      icon: "",
      link: "/",
    },
    {
      name: " Reward Program",
      icon: "",
      link: "/",
    },
    {
      name: "Shipping & Returns",
      icon: "",
      link: "/",
    },
    { name: "Privacy Policy", icon: "", link: "/" },
    { name: "Bulk Editor", icon: "", link: "/" },
    { name: "Blog", icon: "", link: "/" },
  ],
  brands: [
    {
      id: "1",
      name: " Anna",
      icon: "",
      link: "/",
      img: "/assets/images/brands/brand-4.jpg",
    },
    {
      id: "2",
      name: "Benjamin Button",
      icon: "",
      link: "/",
      img: "/assets/images/brands/brand-2.jpg",
    },
    {
      id: "3",
      name: "Burberry",
      icon: "",
      link: "/",
      img: "/assets/images/brands/brand-1.jpg",
    },
    {
      id: "4",
      name: "Carhart",
      icon: "",
      link: "/",
      img: "/assets/images/brands/brand-3.jpg",
    },
    {
      id: "5",
      name: "Chanel",
      icon: "",
      link: "/",
      img: "/assets/images/brands/brand-1.jpg",
    },
    {
      id: "6",
      name: "Coco Lee",
      icon: "",
      link: "/",
      img: "/assets/images/brands/brand-4.jpg",
    },
    {
      id: "7",
      name: "Collette",
      icon: "",
      link: "/",
      img: "/assets/images/brands/brand-1.jpg",
    },
  ],
  paymentMethods: [
    {
      id: 1,
      name: "Visa",
      icon: "/assets/images/bank/visa.png",
    },
    {
      id: 2,
      name: "PayPal",
      icon: "/assets/images/bank/paypal.png",
    },
    {
      id: 3,
      name: "Western",
      icon: "/assets/images/bank/western.png",
    },
    {
      id: 4,
      name: "Master",
      icon: "/assets/images/bank/master.png",
    },
    {
      id: 5,
      name: "Discover",
      icon: "/assets/images/bank/discover.png",
    },
    {
      id: 6,
      name: "Circus",
      icon: "/assets/images/bank/circus.png",
    },
    {
      id: 7,
      name: "American",
      icon: "/assets/images/bank/american.png",
    },
  ],
  policies: [
    {
      id: 1,
      text: "Free Shipping & Returns",
      icon: "far fa-truck-moving",
    },
    {
      id: 2,
      text: "Lowest Price Guarantee",
      icon: "far fa-medal",
    },
    {
      id: 3,
      text: "Longest Warranties Offer",
      icon: "far fa-trophy-alt",
    },
  ],
};
