module.exports = {
  navLinks: [
    {
      name: "home",
      children: [],
      icon: "",
      url: "/",
    },
    {
      name: "products",
      children: [],
      icon: "",
      url: "/products",
    },
    {
      name: "categories",
      children: [
        {
          name: "Accessories & Supplies",
          children: [],
          icon: "",
          url: "/Women",
        },
        {
          name: "Camera & Photo",
          children: [],
          icon: "",
          url: "/Women",
        },
        {
          name: "Car & Vehicle Electronics",
          children: [],
          icon: "",
          url: "/Women",
        },
        {
          name: "Cell Phones & Accessories",
          children: [],
          icon: "",
          url: "/Women",
        },
        {
          name: "Computers & Accessories",
          children: [],
          icon: "",
          url: "/Women",
        },
        {
          name: "GPS & Navigation",
          children: [],
          icon: "",
          url: "/Women",
        },
        {
          name: "Headphones",
          children: [],
          icon: "",
          url: "/Women",
        },
        {
          name: "Home Audio",
          children: [],
          icon: "",
          url: "/Women",
        },
        {
          name: "Office Electronics",
          children: [],
          icon: "",
          url: "/Women",
        },
      ],
      icon: true,
      url: "/women",
    },
    {
      name: "fags",
      children: [],
      icon: "",
      url: "/fags",
    },
    {
      name: "about",
      children: [],
      icon: "",
      url: "/about",
    },
    {
      name: "contact",
      children: [],
      icon: "",
      url: "/contact",
    },
  ],

  contactInfo: [
    {
      name: "685 Market Street",
      icon: "",
      url: "/",
    },
    {
      name: "Cosmopolis, CA 94105, United States",
      icon: "",
      url: "/",
    },
    { name: "1.800.000.6690", icon: "fas fa-phone", url: "/" },
    {
      name: "support@electronry.com",
      icon: "fas fa-envelope",
      url: "/",
    },
  ],
  furtherInfo: [
    { name: "About", icon: "", url: "/" },
    {
      name: "Customer Service",
      icon: "",
      url: "/",
    },
    {
      name: " Reward Program",
      icon: "",
      url: "/",
    },
    {
      name: "Shipping & Returns",
      icon: "",
      url: "/",
    },
    { name: "Privacy Policy", icon: "", url: "/" },
    { name: "Bulk Editor", icon: "", url: "/" },
    { name: "Blog", icon: "", url: "/" },
  ],
  brands: [
    {
      id: "1",
      name: " Sony",
      icon: "",
      url: "/",
      img: "/assets/images/brands/brand-4.jpg",
    },
    {
      id: "2",
      name: "Toshiba",
      icon: "",
      url: "/",
      img: "/assets/images/brands/brand-2.jpg",
    },
    {
      id: "3",
      name: "Panasonic",
      icon: "",
      url: "/",
      img: "/assets/images/brands/brand-1.jpg",
    },
    {
      id: "4",
      name: "Samsung",
      icon: "",
      url: "/",
      img: "/assets/images/brands/brand-3.jpg",
    },
    {
      id: "5",
      name: "Microsoft",
      icon: "",
      url: "/",
      img: "/assets/images/brands/brand-1.jpg",
    },
    {
      id: "6",
      name: "Apple",
      icon: "",
      url: "/",
      img: "/assets/images/brands/brand-4.jpg",
    },
    {
      id: "7",
      name: "Fujitsu",
      icon: "",
      url: "/",
      img: "/assets/images/brands/brand-1.jpg",
    },
  ],
  paymentMethods: [
    {
      id: 1,
      name: "Visa",
      icon: "/assets/images/bank/visa.png",
    },
    {
      id: 2,
      name: "PayPal",
      icon: "/assets/images/bank/paypal.png",
    },
    {
      id: 3,
      name: "Western",
      icon: "/assets/images/bank/western.png",
    },
    {
      id: 4,
      name: "Master",
      icon: "/assets/images/bank/master.png",
    },
    {
      id: 5,
      name: "Discover",
      icon: "/assets/images/bank/discover.png",
    },
    {
      id: 6,
      name: "Circus",
      icon: "/assets/images/bank/circus.png",
    },
    {
      id: 7,
      name: "American",
      icon: "/assets/images/bank/american.png",
    },
  ],
  policies: [
    {
      id: 1,
      text: "Free Shipping & Returns",
      icon: "far fa-truck-moving",
    },
    {
      id: 2,
      text: "Lowest Price Guarantee",
      icon: "far fa-medal",
    },
    {
      id: 3,
      text: "Longest Warranties Offer",
      icon: "far fa-trophy-alt",
    },
  ],
  aboutUs: [
    {
      id: 1,
      name: "Free Shipping On First Order",
      description: "Praesent suscipit mattis facilisis.",
      img: "/assets/images/icon-us-1.png",
      url: "/about-us",
    },
    {
      id: 2,
      name: "Weekly Flash Sale",
      description: "Praesent suscipit mattis facilisis.",
      img: "/assets/images/icon-us-2.png",
      url: "/about-us",
    },
    {
      id: 3,
      name: "Anual Payment Discount",
      description: "Praesent suscipit mattis facilisis.",
      img: "/assets/images/icon-us-3.png",
      url: "/about-us",
    },
    {
      id: 4,
      name: "Cashback Reward Program",
      description: "Praesent suscipit mattis facilisis.",
      img: "/assets/images/icon-us-4.png",
      url: "/about-us",
    },
  ],
};
